# Generated by Django 3.0.5 on 2020-05-08 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('num_people_household', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCommute',
            fields=[
                ('commute_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.User')),
            ],
        ),
        migrations.CreateModel(
            name='Commute',
            fields=[
                ('commute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='calculator.UserCommute')),
                ('car', models.TextField()),
                ('transmission', models.TextField()),
                ('distance', models.FloatField()),
                ('city_perc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserEmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('emission', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.User')),
            ],
        ),
        migrations.CreateModel(
            name='HydroBillField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('num_days', models.SmallIntegerField()),
                ('city', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.User')),
            ],
        ),
        migrations.CreateModel(
            name='FortisBillField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_days', models.SmallIntegerField()),
                ('consumption', models.FloatField()),
                ('avg_temp', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.User')),
            ],
        ),
    ]
