# Generated by Django 3.0.5 on 2020-05-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrobillfield',
            name='consumption',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
