# Generated by Django 3.0.5 on 2020-05-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_hydrobillfield_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='commute',
            name='car_year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
