# Generated by Django 3.0.5 on 2020-04-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('footprint', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
