# Generated by Django 3.0.5 on 2020-05-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
