# Generated by Django 3.0.5 on 2020-05-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_demo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SampleUser',
        ),
    ]
